const wikiGraph = require('./wikigraph')

console.log(wikiGraph.path('Capivara', 'Barack Obama'))
console.log(wikiGraph.path('Capivara', 'Barack Obama'))
console.log(wikiGraph.path('Capivara', 'Barack Obama'))
console.log(wikiGraph.path('Capivara', 'Barack Obama'))
console.log(wikiGraph.path('Capivara', 'Barack Obama'))
console.log(wikiGraph.path('Capivara', 'Barack Obama'))
console.log(wikiGraph.path('Capivara', 'Barack Obama'))
console.log(wikiGraph.path('Capivara', 'Barack Obama'))
console.log(wikiGraph.path('Capivara', 'Barack Obama'))
console.log(wikiGraph.path('Capivara', 'Barack Obama'))
console.log(wikiGraph.path('Capivara', 'Barack Obama'))
console.log(wikiGraph.path('Capivara', 'Barack Obama'))
console.log(wikiGraph.path('Capivara', 'Barack Obama'))
console.log(wikiGraph.path('Capivara', 'Barack Obama'))
console.log(wikiGraph.path('Capivara', 'Barack Obama'))
console.log(wikiGraph.path('Capivara', 'Barack Obama'))
console.log(wikiGraph.path('Capivara', 'Barack Obama'))
console.log(wikiGraph.path('Capivara', 'Barack Obama'))
console.log(wikiGraph.path('Capivara', 'Barack Obama'))
console.log(wikiGraph.path('Capivara', 'Barack Obama'))
console.log(wikiGraph.path('Capivara', 'Barack Obama'))
console.log(wikiGraph.path('Capivara', 'Barack Obama'))
console.log(wikiGraph.path('Capivara', 'Barack Obama'))
console.log(wikiGraph.path('Capivara', 'Barack Obama'))
console.log(wikiGraph.path('Capivara', 'Barack Obama'))
console.log(wikiGraph.path('Capivara', 'Barack Obama'))
